language: ruby
bundler_args: --with travis
cache: bundler
sudo: false
rvm:
  - 2.1.2
script:
# We cannot run integration tests on travis since that uses vagrant/virtualbox and
# is not available in travis ci
  - bundle exec rake unit
  - bundle exec rake style
